const a = [
  {
    id: "3",
    title: "books",
    unitInputType: "number",
    creationDate: new Date("2019-01-01 17:00:00"),
    archived: false,
    TrackingPeriod: "week",
    unit: "times",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "total",
    eventsArray: [],
    endDate: null,
    backgroundPic: null,
  },
  {
    id: "32",
    title: "running",
    unitInputType: "number",
    creationDate: new Date("2019-01-01 17:00:00"),
    archived: false,
    TrackingPeriod: "week",
    unit: "times",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "total",
    eventsArray: [],
    endDate: null,
    backgroundPic: null,
  },
  {
    id: "31",
    title: "sports",
    unitInputType: "number",
    creationDate: new Date("2019-01-01 17:00:00"),
    archived: false,
    TrackingPeriod: "week",
    unit: "times",
    unitDesc: "bla bla bla",
    subjectDesc: "bla bla bla",
    goal: "total",
    eventsArray: [],
    endDate: null,
    backgroundPic: null,
  },
];
module.exports = a;
